language: node_js
node_js: stable
install:
  - yarn install --frozen-lockfile
script:
  - bash ./travis/gh-pages.sh
env:
  global:
  - ENCRYPTION_LABEL: "dd067b5f92cf"
  - COMMIT_AUTHOR_EMAIL: "sh@signalwerk.ch"
  - DEPLOY_DIR: "sites/blog/public"
  - SOURCE_BRANCH: "master"
  - TARGET_BRANCH: "gh-pages"
branches:
  only:
  - master
